{% set version = "0.14.1" %}
{% set sha256 = "78a679ee0c693ced740238b4e4fad766e509f263a45198b007c1692a28e9675d" %}

package:
  name: pysr
  version: {{ version }}

source:
  - url: https://github.com/MilesCranmer/PySR/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win]
requirements:
  host:
    - python
    - pip
    - pyjulia >=0.6.0
    - julia
    - numpy
    # temporarily rebuilding with newest numpy because PyCall.jl ends up
    # reinstalling it and we want to avoid spamming ClobberWarnings
    # TODO: remove this as soon as numpy does not get spuriously installed here anymore
    - numpy >=1.14.0
    - pandas
    - sympy
    - scikit-learn >=1.0.0
    - click >=7.0.0
    - openlibm
    - openspecfun
    - libstdcxx-ng <13
  run:
    - python
    - pyjulia >=0.6.0
    - julia
    - {{ pin_compatible('numpy') }}
    - pandas
    - sympy
    - scikit-learn >=1.0.0
    - click >=7.0.0
    - openlibm
    - openspecfun
  run_constrained:
    - libstdcxx-ng <13

test:
  imports:
    - pysr
  requires:
    - pip
  commands:
    - pip check
    - julia --project=@pysr-{{ version }} -e "using PyCall, SymbolicRegression, ClusterManagers"
    - python -m pysr.test main

about:
  home: https://github.com/MilesCranmer/PySR
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Simple, fast, and parallelized symbolic regression in Python
  description: |
    PySR is a simple, fast, and parallelized symbolic regression package for Python and Julia, which makes use of an algorithm based on regularized evolution and simulated annealing.
  doc_url: https://astroautomata.com/PySR
  dev_url: https://github.com/MilesCranmer/PySR

extra:
  recipe-maintainers:
    - MilesCranmer
