{% set version = "1.0.0" %}
{% set sha256 = "4e34db1f4d61d7c3cd9f98ebeebf7deb22e46532d4ec8c49be025a5faa65b6f3" %}

package:
  name: pysr
  version: {{ version }}

source:
  - url: https://github.com/MilesCranmer/PySR/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
requirements:
  host:
    - python >=3.10,<4.0
    - pip
    - sympy >=1.0.0,<2.0.0
    - pandas >=0.21.0,<3.0.0
    - numpy >=1.13.0,<3.0.0
    - scikit-learn >=1.0.0,<2.0.0
    - pyjuliacall >=0.9.23,<0.9.24
    - click >=7.0.0,<9.0.0
  run:
    - python >=3.10,<4.0
    - {{ pin_compatible('numpy') }}
    - sympy >=1.0.0,<2.0.0
    - pandas >=0.21.0,<3.0.0
    - scikit-learn >=1.0.0,<2.0.0
    - pyjuliacall >=0.9.23,<0.9.24
    - click >=7.0.0,<9.0.0
    - setuptools >=50.0.0

test:
  imports:
    - pysr
  requires:
    - pip
  commands:
    - pip check
    - python -m pysr test main

about:
  home: https://github.com/MilesCranmer/PySR
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Simple, fast, and parallelized symbolic regression in Python
  description: |
    PySR is a simple, fast, and parallelized symbolic regression package for Python and Julia, which makes use of an algorithm based on regularized evolution and simulated annealing.
  doc_url: https://ai.damtp.cam.ac.uk/pysr
  dev_url: https://github.com/MilesCranmer/PySR

extra:
  recipe-maintainers:
    - MilesCranmer
