{% set version = "0.10.0" %}

package:
  name: pysr
  version: {{ version }}

source:
  - url: https://github.com/MilesCranmer/PySR/archive/v{{ version }}.tar.gz
    sha256: 92225729d84f12b5d2c9143b2d6f2e2beffa07c6e23b0efaef8069cb70f001ab

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - pip
  run:
    - python >=3.6,<4.0
    - pyjulia >=0.5.7
    - julia >=1.6.0
    - numpy >=1.14.0
    - pandas
    - sympy
    - scikit-learn >=1.0.0

test:
  imports:
    - pysr
  requires:
    - pip
  commands:
    - pip check
    # Smoke test for starting PyJulia:
    - python -c 'from pysr.sr import init_julia; init_julia()'
    # Smoke test for running model:
    - python -c 'import numpy as np; from pysr import PySRRegressor; X = np.random.randn(100,1); y = X[:, 0]**3; PySRRegressor().fit(X, y).predict(X)'

about:
  home: https://github.com/MilesCranmer/PySR
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Simple, fast, and parallelized symbolic regression in Python
  description: |
    PySR is a simple, fast, and parallelized symbolic regression package for Python and Julia, which makes use of an algorithm based on regularized evolution and simulated annealing.
  doc_url: https://astroautomata.com/PySR
  dev_url: https://github.com/MilesCranmer/PySR

extra:
  recipe-maintainers:
    - MilesCranmer
