{% set version = "0.7.2" %}

package:
  name: pysr
  version: {{ version }}

source:
  - url: https://github.com/MilesCranmer/PySR/archive/v{{ version }}.tar.gz
    sha256: e26de6e08636a40f30cdb5f2f3af20f4a9a3f6b1a083ef530ff5697642bb909d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv && {{ PYTHON }} -c 'import pysr; pysr.install()'"

requirements:
  build:
    - python
    - pip
    - pyjulia >=0.5.7
  host:
    - python >=3.6,<4.0
    - pip
    - pyjulia >=0.5.7
    - numpy >=1.14.0
    - pandas
    - sympy
    - scikit-learn
    - openlibm <0.8.0
  run:
    - python >=3.6,<4.0
    - {{ pin_compatible('pyjulia') }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pandas') }}
    - {{ pin_compatible('sympy') }}
    - {{ pin_compatible('scikit-learn') }}
    - {{ pin_compatible('openlibm') }}

test:
  imports:
    - pysr
  requires:
    - pip
  commands:
    - pip check
    - python -c 'import pysr; pysr.install(); from pysr.sr import init_julia; init_julia()'

about:
  home: https://github.com/MilesCranmer/PySR
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Simple, fast, and parallelized symbolic regression in Python'
  description: |
    PySR is a simple, fast, and parallelized symbolic regression package for Python and Julia, which makes use of an algorithm based on regularized evolution and simulated annealing.
  doc_url: https://astroautomata.com/PySR
  dev_url: https://github.com/MilesCranmer/PySR

extra:
  recipe-maintainers:
    - MilesCranmer
