{% set version = "0.17.0" %}
{% set sha256 = "ec4069c24c534af992d4283ef4688e762a365efe2725b6e53c887ffa0c7113f3" %}

package:
  name: pysr
  version: {{ version }}

source:
  - url: https://github.com/MilesCranmer/PySR/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
requirements:
  host:
    - python
    - pip
    - pyjulia >=0.6.0
    - julia
    - numpy
    - pandas
    - sympy
    - scikit-learn >=1.0.0
    - click >=7.0.0
    - openlibm
    - openspecfun >=0.5.5,<0.5.6
  run:
    - python
    - pyjulia >=0.6.0
    - julia
    - {{ pin_compatible('numpy') }}
    - pandas
    - sympy
    - scikit-learn >=1.0.0
    - click >=7.0.0
    - openlibm
    - openspecfun >=0.5.5,<0.5.6

test:
  imports:
    - pysr
  requires:
    - pip
  commands:
    - pip check
    - julia --project=@pysr-{{ version }} -e "using PyCall, SymbolicRegression, ClusterManagers"
    - python -m pysr.test main

about:
  home: https://github.com/MilesCranmer/PySR
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Simple, fast, and parallelized symbolic regression in Python
  description: |
    PySR is a simple, fast, and parallelized symbolic regression package for Python and Julia, which makes use of an algorithm based on regularized evolution and simulated annealing.
  doc_url: https://astroautomata.com/PySR
  dev_url: https://github.com/MilesCranmer/PySR

extra:
  recipe-maintainers:
    - MilesCranmer
