{% set version = "0.11.7" %}
{% set sha256 = "a8f6aa390492027804193cf2f7f5317dc1a0c6f41f7f3fc83be3f880f397c6b6" %}

package:
  name: pysr
  version: {{ version }}

source:
  - url: https://github.com/MilesCranmer/PySR/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
requirements:
  host:
    - python
    - pip
    - pyjulia >=0.5.7
    - julia
    - numpy >=1.14.0
    - pandas
    - sympy
    - scikit-learn
    - openlibm
    - openspecfun
  run:
    - python
    - pyjulia >=0.5.7
    - julia
    - numpy >=1.14.0
    - pandas
    - sympy
    - scikit-learn
    - openlibm
    - openspecfun

test:
  imports:
    - pysr
  requires:
    - pip
  commands:
    - pip check
    - julia --project=@pysr-{{ version }} -e "using PyCall, SymbolicRegression, ClusterManagers"
    - python -c 'from pysr.sr import init_julia; init_julia()'
    - python -c 'import pysr; pysr.install(); from pysr.sr import init_julia; init_julia()'
    - python -c 'import tempfile; tempenv = tempfile.mkdtemp(); import pysr; pysr.install(tempenv); from pysr.sr import init_julia; init_julia(tempenv)'

about:
  home: https://github.com/MilesCranmer/PySR
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Simple, fast, and parallelized symbolic regression in Python
  description: |
    PySR is a simple, fast, and parallelized symbolic regression package for Python and Julia, which makes use of an algorithm based on regularized evolution and simulated annealing.
  doc_url: https://astroautomata.com/PySR
  dev_url: https://github.com/MilesCranmer/PySR

extra:
  recipe-maintainers:
    - MilesCranmer
